use std::collections::HashSet;
use std::fs;
use std::path::Path;

use walkdir::WalkDir;

fn main() {
    println!("cargo:rerun-if-changed=i18n/");

    let keys = collect_all_keys("i18n/zh-CN");
    generate_keys_module(&keys);
}

fn collect_all_keys(dir: &str) -> HashSet<String> {
    let mut keys = HashSet::new();

    for entry in WalkDir::new(dir).into_iter().filter_map(|e| e.ok()) {
        if entry.path().extension().and_then(|s| s.to_str()) != Some("ftl") {
            continue;
        }

        let content = fs::read_to_string(entry.path()).unwrap();
        for line in content.lines() {
            let line = line.trim();
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            if let Some(key) = line.split('=').next() {
                let key = key.trim();
                if !key.is_empty() {
                    keys.insert(key.to_string());
                }
            }
        }
    }

    keys
}

fn generate_keys_module(keys: &HashSet<String>) {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("generated_keys.rs");

    let mut code = String::from("// Auto-generated by build.rs - DO NOT EDIT\n\n");
    code.push_str("#[allow(dead_code)]\n");
    code.push_str("pub mod keys {\n");

    let mut sorted_keys: Vec<_> = keys.iter().collect();
    sorted_keys.sort();

    for key in sorted_keys {
        let const_name = key.to_uppercase().replace('-', "_");
        code.push_str(&format!(
            "    pub const {}: &str = \"{}\";\n",
            const_name, key
        ));
    }

    code.push_str("}\n");

    fs::write(&dest_path, code).unwrap();
}
